# http://iec.ch/TC57/ns/CIM/Equipment-EU/constraints/IEC61970-301/notSolved/3.0#ACLineSegment-baseVoltage
# ACLineSegment-baseVoltage
# The BaseVoltage at the two ends of ACLineSegments in a Line shall have the same BaseVoltage.nominalVoltage. However, boundary lines may have slightly different BaseVoltage.nominalVoltages and variation is allowed. Larger voltage difference in general requires use of an equivalent branch.

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


			SELECT $this ?voltage1 ?voltage2
			WHERE {
        ?terminal1 cim:Terminal.ConductingEquipment $this .
        ?terminal2 cim:Terminal.ConductingEquipment $this .
        ?terminal1 cim:ACDCTerminal.sequenceNumber 1 .
        ?terminal2 cim:ACDCTerminal.sequenceNumber 2 .
        ?terminal1 cim:Terminal.TopologicalNode ?topologicalnode1 .
        ?terminal2 cim:Terminal.TopologicalNode ?topologicalnode2 .
        ?topologicalnode1 cim:TopologicalNode.BaseVoltage/cim:BaseVoltage.nominalVoltage ?voltage1 .
        ?topologicalnode2 cim:TopologicalNode.BaseVoltage/cim:BaseVoltage.nominalVoltage ?voltage2 .
				FILTER (?terminal1 != ?terminal2 && ?voltage1 != ?voltage2 && ?topologicalnode1 != ?topologicalnode2) .
			}