# http://iec.ch/TC57/ns/CIM/SteadyStateHypothesis-EU/constraints/IEC61970-301/notSolved/3.0#CsConverter.targetAlpha-applicability
# CsConverter.targetAlpha-applicability
# It is only applicable for rectifier if continuous tap changer control is used.

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


			SELECT  $this ?value
			WHERE {
        #OPTIONAL {$this $PATH ?value}.
        $this $PATH ?value.
        $this cim:CsConverter.operatingMode ?opermode .
        #OPTIONAL {$this cim:ACDCConverter.PccTerminal ?pccterminal}.
        #OPTIONAL {?pccterminal cim:Terminal.ConductingEquipment ?condeq}. 
        #OPTIONAL {?condeq rdf:type ?condeqtype}.
        #OPTIONAL {?pccterminal cim:RegulatingControl.Terminal ?regcontrol}.
        #OPTIONAL {?regcontrol cim:RegulatingControl.discrete ?discrete}.
        
        OPTIONAL {$this cim:ACDCConverter.PccTerminal ?pccterminal .
                  ?pccterminal cim:Terminal.ConductingEquipment/rdf:type cim:PowerTransformer .
                  ?pccterminal ^cim:RegulatingControl.Terminal/cim:RegulatingControl.discrete ?discrete .
        } .
        
        
        #?regcontrol cim:RegulatingControl.Terminal ?pccterm .
        #FILTER (bound(?value) && (?opermode=cim:CsOperatingModeKind.inverter || (bound(?pccterminal) && ?condeqtype=cim:PowerTransformer && ?discrete=true && ?pccterm=?pccterminal))) .   
        FILTER ((?opermode=cim:CsOperatingModeKind.inverter || (bound(?pccterminal)  && ?discrete=true) || !bound(?discrete) )) .          
			}