# http://iec.ch/TC57/ns/CIM/Equipment-EU/constraints/IEC61970-301/3.0#PowerTransformerEnd.ratedS-valueRange2winding
# PowerTransformerEnd.ratedS-valueRange2winding
# For a two-winding transformer the values for the high and low voltage sides shall be identical. 

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


			SELECT  $this ?value ?ends
			WHERE {
        {
        SELECT $this (COUNT(?typeend) AS ?ends)
        WHERE {
        $this ^cim:PowerTransformerEnd.PowerTransformer/rdf:type ?typeend .
        }
        GROUP BY $this ?typeend
        }
        
        ?end1 cim:PowerTransformerEnd.PowerTransformer $this .
        ?end1 cim:TransformerEnd.endNumber  1.
        ?end1 cim:PowerTransformerEnd.ratedS  ?value .
        #OPTIONAL {?end1 cim:PowerTransformerEnd.ratedS  ?value }.
        BIND(EXISTS{?end1 cim:PowerTransformerEnd.ratedS  ?v} AS ?hasvalue).
        ?end2 cim:PowerTransformerEnd.PowerTransformer $this  .
        ?end2 cim:TransformerEnd.endNumber  2 .
        ?end2 cim:PowerTransformerEnd.ratedS  ?ratedsend2 .
        BIND(EXISTS{?end2 cim:PowerTransformerEnd.ratedS  ?r} AS ?hasratedsend2).
        #OPTIONAL {?end2 cim:PowerTransformerEnd.ratedS  ?ratedsend2 }.

        FILTER (?hasvalue=true && ?hasratedsend2=true && ?end1!=?end2 && ?value!=?ratedsend2) .        
			}
      HAVING(?ends=2)
      