# http://iec.ch/TC57/ns/CIM/Topology-EU/constraints/IEC61970-456/notSolved/3.0#Switch-sameTopologicalNode
# Switch-sameTopologicalNode
# The Terminal-s of the two sides of a retained Switch (Switch.retained=true) or any of its subclasses shall not be connected to the same TopologicalNode.

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


			SELECT  $this ?value ?cntn1 ?tn1
			WHERE {
             $this $PATH ?value .
             ?terminal1 cim:Terminal.ConductingEquipment $this .
             ?terminal1 cim:ACDCTerminal.sequenceNumber 1 .
             OPTIONAL {?terminal1 cim:Terminal.ConnectivityNode ?cn1}.
             OPTIONAL {?terminal1 cim:Terminal.TopologicalNode ?tn1}.
             ?cn1 cim:ConnectivityNode.TopologicalNode ?cntn1 .
             
             ?terminal2 cim:Terminal.ConductingEquipment $this .
             ?terminal2 cim:ACDCTerminal.sequenceNumber 2 .
             OPTIONAL {?terminal2 cim:Terminal.ConnectivityNode ?cn2}.
             OPTIONAL {?terminal2 cim:Terminal.TopologicalNode ?tn2}.
             ?cn2 cim:ConnectivityNode.TopologicalNode ?cntn2 .          
				FILTER (?value=true && (?terminal1!=?terminal2 && (?tn1=?tn2 || ?cntn1=?cntn2))) .
			}