# http://iec.ch/TC57/ns/CIM/Equipment-EU/constraints/IEC61970-452/3.0#SynchronousMachine.type-condenser
# SynchronousMachine.type-condenser
# The SynchronousMachine is not required to be associated with a GeneratingUnit via the association RotatingMachine.GeneratingUnit in cases where a synchronous condenser is being modelled as there is no capability for real power output. In this case, the SynchronousMachine.type shall be set to condenser. The following SynchronousMachine.type-s: motorOrCondenser, generatorOrCondenser, and generatorOrCondenserOrMotor are not allowed to use.

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


	      SELECT $this ?value 
        WHERE {
        $this $PATH ?value .
        $this $PATH cim:SynchronousMachineKind.condenser  .
        OPTIONAL {$this cim:RotatingMachine.GeneratingUnit ?genunit } .
        #BIND(EXISTS{$this cim:RotatingMachine.GeneratingUnit ?genunit} AS ?opt).
        #FILTER (?opt=true && ?value=cim:SynchronousMachineKind.condenser ).
        FILTER (bound(?genunit) ).
        }