# http://iec.ch/TC57/ns/CIM/Topology-EU/constraints/IEC61970-600/notSolved/3.0#Terminal-EXCH8TopologicalNode
# Terminal-EXCH8TopologicalNode
# The association end Terminal.TopologicalNode is required in cases where a RegulatingControl is associated with a Terminal.

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


			SELECT  $this 
			WHERE {
             #OPTIONAL {$this ^cim:RegulatingControl.Terminal ?rc}.
             #OPTIONAL {$this cim:Terminal.TopologicalNode ?value}.
             #BIND(EXISTS{$this ^cim:RegulatingControl.Terminal/cim:RegulatingControl.enabled true} AS ?enable).
             BIND(EXISTS{$this ^cim:RegulatingControl.Terminal ?rc} AS ?rctrue).
             BIND(EXISTS{$this cim:Terminal.TopologicalNode ?v} AS ?val).
             #$this cim:Terminal.TopologicalNode ?value .
				#FILTER (!bound(?value) && bound(?rc)) .
        #FILTER (?val=false && ?enable=true) .
        FILTER (?val=false && ?rctrue=true) .
			}