# https://ap-con.cim4.eu/DatasetMetadata-Simple/3.0#usedSettings-NC-cardinality
# usedSettings-NC-cardinality
# This constraint validates the cardinality of the property (attribute).

PREFIX adms:    <http://www.w3.org/ns/adms#>
PREFIX cim:     <https://cim.ucaiug.io/ns#>
#PREFIX cim:    <http://iec.ch/TC57/CIM100#>
PREFIX cim16:   <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX cim17:   <http://iec.ch/TC57/CIM100#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX dcatcim: <https://cim4.eu/ns/dcatcim#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dm:      <http://iec.ch/TC57/61970-552/DifferenceModel/1#>
PREFIX eu:      <https://cim.ucaiug.io/ns/eu#>
#PREFIX eu:     <http://iec.ch/TC57/CIM100-European#>
PREFIX md:      <http://iec.ch/TC57/61970-552/ModelDescription/1#>
PREFIX nc:      <https://cim4.eu/ns/nc#>
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>


	      SELECT $this ?value ?v
        WHERE {
		$this dcterms:conformsTo ?conformsTo .
		{
			SELECT $this (count(?value) as ?v)
			WHERE {
			OPTIONAL {$this $PATH ?value } .
			}
			GROUP BY $this $PATH 
		}
        FILTER (?v=0 && ?conformsTo IN (<https://ap.cim4.eu/SecurityAnalysisResult/2.4> )).
        }